### ISSUE TITLE
Summary

### ISSUE THREAD

**Issue by farishkash** [Sitejacket/prj-rev-bwfs-dasmoto#1]
Overall excellent, you met everything I am looking for in this project.  You used divs to organize each section and your css wasn't overly repetitive.  Your css is very well done and manages everything correctly.

As you progress through these projects you will start using flexbox. To prepare you for this go to flexboxfroggy.com and see how far you can get in this game. It will help you understand the fundamentals of flexbox.

**Comment by Qasiel** [comment]
Feedback received and very happy with the outcome!
